version: '3.5'

services:
  mysqldb:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - 3306:3306
    environment:
      - DB_HOST=mysqldb
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=groot
      - MYSQL_ROOT_USER=admin
      - MYSQL_PASSWORD=password
    networks:
      - web



  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8030:80
    environment:
      - PMA_HOST=mysqldb
      - UPLOAD_LIMIT=300M
    networks:
      - web
    depends_on:
      - mysqldb

volumes:
  mysql_data_db:


networks:
  web:
    external: true
