version: '3.5'

services:
  groot:
    build: 
      context: .
      target: 'groot'
    volumes:
     - .:/app
    networks:
      - web
    ports:
      - 8000:8000
    environment:
      NODE_ENV: production
      TZ: America/Bogota
      VIRTUAL_HOST: groot.backsoul.dev
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: groot.backsoul.dev
      LETSENCRYPT_EMAIL: danielsarmientoenterprise@gmail.com


networks:
  web:
    external: true