version: '3.5'

services:
  groot:
    build: 
      context: .
      target: 'groot'
    volumes:
     - .:/app
    ports:
      - 3000:3000
    networks:
      - db

networks:
  db:
    external: true